const darkTheme = {
  mode: 'dark',
  PRIMARY_BACKGROUND_COLOR: '#2A2B2E',
  SECONDARY_BACKGROUND_COLOR: '#404146',
  PRIMARY_TEXT_COLOR: '#FFF',
  SECONDARY_TEXT_COLOR: '#323337',
  ACTIVE_TEXT_COLOR: '#FF3367',
  INACTIVE_TEXT_COLOR: '#868D94',
  PRIMARY_BUTTON_BACKGROUND_COLOR: '#FF3367',
  PRIMARY_BUTTON_COLOR: '#FFF',
  PLACEHOLDER_TEXT_COLOR: '#868D94',
  ERROR_TEXT_COLOR: '#FF3367',
  BAR_STYLE: 'light-content',
};

const lightTheme = {
  mode: 'light',
  PRIMARY_BACKGROUND_COLOR: '#ECECEC',
  SECONDARY_BACKGROUND_COLOR: '#FFF',
  PRIMARY_TEXT_COLOR: '#FF3367',
  SECONDARY_TEXT_COLOR: '#FFF',
  ACTIVE_TEXT_COLOR: '#FF3367',
  INACTIVE_TEXT_COLOR: '#A5ADB5',
  PRIMARY_BUTTON_BACKGROUND_COLOR: '#FF3367',
  PRIMARY_BUTTON_COLOR: '#FFF',
  PLACEHOLDER_TEXT_COLOR: '#A5ADB5',
  ERROR_TEXT_COLOR: '#FF3367',
  BAR_STYLE: 'dark-content',
};

export default themes = {darkTheme, lightTheme};
