const darkTheme = {
    mode: 'dark',
    PRIMARY_BACKGROUND_COLOR: '#2A2B2E',
    SECONDARY_BACKGROUND_COLOR: '#404146',
    PRIMARY_TEXT_COLOR: '#FFF',
    SECONDARY_TEXT_COLOR: '#323337',
    PRIMARY_BUTTON_BACKGROUND_COLOR: '#FF3367',
    PRIMARY_BUTTON_COLOR: '#FFF'
}

const lightTheme = {
    mode: 'light',
    PRIMARY_BACKGROUND_COLOR: '#ECECEC',
    SECONDARY_BACKGROUND_COLOR: '#FFF',
    PRIMARY_TEXT_COLOR: '#DB7093',
    SECONDARY_TEXT_COLOR: '#FFF',
    PRIMARY_BUTTON_BACKGROUND_COLOR: '#FF3367',
    PRIMARY_BUTTON_COLOR: '#FFF'
}

export default themes = { darkTheme, lightTheme }